#!/bin/bash

#--------------------------------------------------------------------------------#
# Tool to create a Bitcoin burn address for committing files to the
# blockchain. The valid address is generated by using the sha256 hash
# of the file contents in place of a public ECDSA key in the steps
# linked below.
#
# https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses 
#--------------------------------------------------------------------------------#

S1=$( cat $1 )
S2=$( echo -n $S1 | openssl dgst -sha256 -binary | xxd -p -c 256 )
S3=$( echo -n $S2 | xxd -r -p | openssl dgst -rmd160 -binary | xxd -p )
S4="00"$S3
S5=$( echo -n $S4 | xxd -r -p | openssl dgst -sha256 -binary | xxd -p -c 256 )
S6=$( echo -n $S5 | xxd -r -p | openssl dgst -sha256 -binary | xxd -p -c 256 )
S7=$( echo -n $S6 | head -c 8 )
S8=$S4$S7

ADDR=$( echo -n $S8 | xxd -r -p | base58 )

echo $ADDR
